"""empty message

Revision ID: e98a3ccb25e5
Revises: 
Create Date: 2019-09-11 18:44:37.993879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98a3ccb25e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filemetadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('sha1', sa.String(), nullable=True),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('md5'),
    sa.UniqueConstraint('sha1'),
    schema='filemetadata'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filemetadata', schema='filemetadata')
    # ### end Alembic commands ###
